public class MODIFIER {

    //  ACCESS MODIFIER IS USED TO "RESTRICT" THE DATA-FIELD,METHODS,CONSTRUCTOR FROM THE OTHER CLASSS/USER
    // THERE ARE TOTAL FOUR TYPES OF ACCESS MODIFIER:-
       // 1) DEFAULT
       // 2) PUBLIC
       // 3) PROTECTED
       // 4) PRIVATE

    // PUBLIC:-
    // IT IS A ACCESS MODIFIER WHEN WE USED IT WITH DATA-FIELD,METHODS,CONSTRUCTOR
    // ALL OF THE DATA ARE ACCESSABLE TO OTHER CLASS IN SAME PACKAGE AND OTHER PACKAGE

    // PRIVATE:- (CLASS CANNOT BE PRIVATE)  (PRIVATE CONSTRUCTOR ONLY HELP TO CREATE OBJECT IN THE SAME CLASS)
    // IT IS A ACCESS MODIFIER WHEN WE USED IT WITH DATA-FIELD,METHODS,CONSTRUCTOR
    // ITS WILL NOT ALLOW THE DATA IN OTHER CLASS OR PACKAGE EXCEPT ITS OWN CLASS

    // PROTECTED:- (USED IN THE INHERITANCE)
    // IT IS A ACCESS MODIFIER WHEN WE USED IT WITH DATA-FIELD,METHODS,CONSTRUCTOR
    // ITS WILL ONLY MAKE THE DATA TO ACCESS IN OTHER CLASSES OF SAME PACKAGE AND SUB-CLASS
    // OF ATHER PACKAGE

    // DEFAULT:- (IF YOU IMPORT THE PACKAGE IT WILL STILL GIVE ERROR)
    //IT IS A ACCESS MODIFIER WHEN WE USED IT WITH DATA-FIELD,METHODS,CONSTRUCTOR
    // IT WILL ONLY ACCESS IN THE OTHER CLASSES OF SAME PACKAGE

    // CLASSES AND INTERFACES CANNOT BE PRIVATE AND PROTECTED
    //

    //   DATA-FIELD
    public String name;  // PUBLIC
    private int age;  // PRIVATE
    protected char grade;  // PROTECTED
    String cast;  // DEFAULT

    // METHODS
    public static void myMethod(int a){}  // PUBLIC
    private static void myMethod(String b){}  // PRIVATE
    protected static void myMethod(double c){}  // PROTECTED
    static void myMethod(char d){}  // DEFAULT

    // CONSTRUCTOR
    public MODIFIER(){} // PUBLIC
    private MODIFIER(int a){}  // PRIVATE
    protected MODIFIER(String b){} // PROTECTED
    MODIFIER(double c){}  // DEFAULT



}
