public class PACKAGE {

    // PACKAGE ARE THE GROUP OF CLASSES STORED IN THE FORM OF PACK
    // HELP TO ORGANIZED THE CLASSES AND INTERFACE

    // THERE ARE TWO TYPE OF PACKAGE:-
       // 1) BUILT-IN-PACKAGE
       // 2) USER-CREATED PACKAGE

    // SUCH AS JAVA.UTIL.SCANNER:-
       // 1) JAVA-->MAIN PACKKAGE
       // 2) UTIL-->SUB PACKAGE
       // 3) SCANNER--> CLASS INSIDE THE PACKAGE

    // LET YOU CREATE THE PACKAGE (ABC PACKAGE) AND CREATE THE CALCULATOR CLASS IN IT

    // IMPORTING THE PACKAGE --> IMPORT ABC PACKAGE IN SECOND LINE AFTER THE PACKAGE NAME IN WHICH THIS CLASS IS STORED

    // WHEN TWO PACKAGE HAVE SAME NAME OF CLASS
       // ABC PACKAGE-->MOIZ CLASS
       // XYZ PACKAGE--> MOIZ CLASS
       // NOW YOU HAVE TO DEFINE IN DETAIL ( ABD PACKAGE . MOIZ() AND XYZ PACKAGE . MOIZ)

    // PACKAGE HAS CLASS (MOIZ,MOMO)
    // PACKAGE ALSO HAVE SUB PACKAGE WITH CLASS (ANAS,SONU)
    // NOW YOU HAVE TO IMPORT BOTH THE PACKAGE
    // IMPORTY ABCPACKAKE  AND IMPORT ABCPACKAGE.SUBPACKAGE



}


